version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 3
    reviewers:
      - r-k-b
    cooldown:
      default-days: 10
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
